import type { CatalogReferenceSource } from "./types";

// Real, reputable, digital-first sources only. Every URL/provider below is
// verbatim from the platform owner's vetted list — do NOT add fabricated
// sources, providers or URLs. Hardware-centric sources (micro:bit, Raspberry
// Pi) are used simulator-first / project-first; never as a hardware requirement.
export const REFERENCE_SOURCES: CatalogReferenceSource[] = [
  {
    key: "scratchjr",
    name: "ScratchJr",
    url: "https://www.scratchjr.org/",
    provider: "ScratchJr (DevTech Research Group, MIT Media Lab & others)",
    sourceType: "Visual coding app",
    relatedTopics: ["visual coding", "interactive stories", "sequencing", "characters", "animation", "simple games"],
    recommendedAgeRange: "5-7",
    usageInSchulab: "Block-based first-coding for ages 5–7: interactive stories, animation, sequencing and simple games.",
    status: "ACTIVE",
  },
  {
    key: "scratch",
    name: "Scratch",
    url: "https://scratch.mit.edu/",
    provider: "Scratch Foundation / MIT Media Lab",
    sourceType: "Block-based coding platform",
    relatedTopics: ["block coding", "animation", "games", "interactive stories", "creative coding"],
    recommendedAgeRange: "8-13",
    usageInSchulab: "Core block-based coding for ages 8+: animation, games, interactive stories and creative coding projects.",
    status: "ACTIVE",
  },
  {
    key: "code-org",
    name: "Code.org",
    url: "https://code.org/",
    provider: "Code.org",
    sourceType: "K–12 computer science curriculum",
    relatedTopics: ["computer science", "AI literacy", "coding fundamentals", "digital citizenship", "web", "programming concepts"],
    recommendedAgeRange: "3-18",
    usageInSchulab: "K–12 CS scope and sequence: coding fundamentals, AI literacy, digital citizenship and web/programming concepts.",
    status: "ACTIVE",
  },
  {
    key: "tynker",
    name: "Tynker",
    url: "https://www.tynker.com/",
    provider: "Tynker",
    sourceType: "Game-based coding platform",
    relatedTopics: ["beginner coding", "creative coding", "game-based learning", "AI/ML introduction", "block coding progression"],
    recommendedAgeRange: "5-14",
    usageInSchulab: "Beginner-to-intermediate creative and game-based coding, plus an introduction to AI/ML for kids.",
    status: "ACTIVE",
  },
  {
    key: "create-learn",
    name: "Create & Learn",
    url: "https://www.create-learn.us/",
    provider: "Create & Learn",
    sourceType: "Online coding classes",
    relatedTopics: ["online coding", "AI for kids", "Python", "virtual robotics", "project-based learning"],
    recommendedAgeRange: "11-18",
    usageInSchulab: "Online-class model for AI, Python and virtual robotics; project-based, fully digital delivery.",
    status: "ACTIVE",
  },
  {
    key: "makecode",
    name: "Microsoft MakeCode",
    url: "https://www.microsoft.com/en-us/makecode",
    provider: "Microsoft",
    sourceType: "Simulator-first coding platform",
    relatedTopics: ["block coding", "JavaScript progression", "Python progression", "MakeCode Arcade", "simulator-first coding"],
    recommendedAgeRange: "8-16",
    usageInSchulab: "Simulator-first block→JavaScript→Python progression and MakeCode Arcade game building. No hardware required.",
    status: "ACTIVE",
  },
  {
    key: "app-inventor",
    name: "MIT App Inventor",
    url: "https://appinventor.mit.edu/",
    provider: "MIT",
    sourceType: "App development platform",
    relatedTopics: ["app development", "mobile app prototypes", "AI app projects"],
    recommendedAgeRange: "12-18",
    usageInSchulab: "Mobile app prototyping and AI-related app projects for older students.",
    status: "ACTIVE",
  },
  {
    key: "khan-computing",
    name: "Khan Academy Computing",
    url: "https://www.khanacademy.org/computing",
    provider: "Khan Academy",
    sourceType: "Computing curriculum",
    relatedTopics: ["JavaScript", "HTML/CSS", "web development", "programming foundations", "computing concepts"],
    recommendedAgeRange: "13-18",
    usageInSchulab: "JavaScript, HTML/CSS, web development and programming foundations for teens.",
    status: "ACTIVE",
  },
  {
    key: "nasa-space-place",
    name: "NASA Space Place",
    url: "https://spaceplace.nasa.gov/",
    provider: "NASA",
    sourceType: "Space & Earth science activities",
    relatedTopics: ["space science", "Earth science", "solar system", "astronomy", "space games"],
    recommendedAgeRange: "7-13",
    usageInSchulab: "Primary space-science source: solar system, astronomy, Earth-from-space and NASA digital STEM activities.",
    status: "ACTIVE",
    notes: "Existing platform space courses are mapped to this source and marked IMPORTED_EXISTING.",
  },
  {
    key: "esa-kids",
    name: "ESA Kids / ESA Space for Kids",
    url: "https://www.esa.int/kids/en/home",
    provider: "European Space Agency (ESA)",
    sourceType: "Space science for children",
    relatedTopics: ["space science", "European space missions", "satellites", "planets", "Earth observation", "astronomy"],
    recommendedAgeRange: "7-13",
    usageInSchulab: "European space missions, satellites, Earth observation and astronomy for children.",
    status: "ACTIVE",
  },
  {
    key: "phet",
    name: "PhET Interactive Simulations",
    url: "https://phet.colorado.edu/",
    provider: "University of Colorado Boulder",
    sourceType: "Science & math simulations",
    relatedTopics: ["physics", "chemistry", "math", "Earth science", "digital experiments"],
    recommendedAgeRange: "9-18",
    usageInSchulab: "Interactive science and math simulations for digital experiments (forces, energy, waves, chemistry).",
    status: "ACTIVE",
  },
  {
    key: "ck12",
    name: "CK-12 Foundation",
    url: "https://www.ck12.org/",
    provider: "CK-12 Foundation",
    sourceType: "Digital STEM content & practice",
    relatedTopics: ["science content", "math content", "FlexBooks", "adaptive practice", "STEM enrichment"],
    recommendedAgeRange: "9-18",
    usageInSchulab: "Digital science/math FlexBooks and adaptive practice for STEM enrichment.",
    status: "ACTIVE",
  },
  {
    key: "raspberry-pi",
    name: "Raspberry Pi Foundation Projects",
    url: "https://projects.raspberrypi.org/",
    provider: "Raspberry Pi Foundation",
    sourceType: "Project-based coding",
    relatedTopics: ["Scratch projects", "Python projects", "HTML/CSS projects", "digital making", "project-based coding"],
    recommendedAgeRange: "8-18",
    usageInSchulab: "Project-based Scratch, Python and HTML/CSS making. Used digital-first; no hardware requirement.",
    status: "ACTIVE",
  },
  {
    key: "code-club",
    name: "Code Club Projects",
    url: "https://codeclub.org/",
    provider: "Raspberry Pi Foundation",
    sourceType: "Youth coding projects",
    relatedTopics: ["creative coding", "Scratch", "Python", "HTML/CSS", "youth coding"],
    recommendedAgeRange: "8-16",
    usageInSchulab: "Creative youth coding projects across Scratch, Python and HTML/CSS.",
    status: "ACTIVE",
  },
  {
    key: "natgeo-kids",
    name: "National Geographic Kids",
    url: "https://kids.nationalgeographic.com/",
    provider: "National Geographic",
    sourceType: "Science enrichment",
    relatedTopics: ["Earth science", "animals", "geography", "environment", "space curiosity"],
    recommendedAgeRange: "5-13",
    usageInSchulab: "Enrichment only: Earth science, environment and space curiosity articles, quizzes and images.",
    status: "ENRICHMENT",
  },
  {
    key: "smithsonian-ssec",
    name: "Smithsonian Science Education Center",
    url: "https://ssec.si.edu/",
    provider: "Smithsonian Institution",
    sourceType: "Inquiry-based science",
    relatedTopics: ["inquiry-based science", "STEM activities", "K–12 science", "science project design"],
    recommendedAgeRange: "9-14",
    usageInSchulab: "Enrichment only: inquiry-based science activities and science-project design models.",
    status: "ENRICHMENT",
  },
  {
    key: "microbit",
    name: "micro:bit / MakeCode micro:bit",
    url: "https://microbit.org/",
    provider: "Micro:bit Educational Foundation",
    sourceType: "Simulator-first physical computing",
    relatedTopics: ["simulator-first coding", "block coding", "JavaScript/Python transition", "computational thinking"],
    recommendedAgeRange: "10-16",
    usageInSchulab: "Simulator-first block→JavaScript/Python coding via https://makecode.microbit.org/ — used entirely in-browser, no hardware required.",
    status: "OPTIONAL",
    notes: "Hardware optional only for offline workshops/camps; the main SchuLab experience uses the online simulator.",
  },
  {
    key: "outschool",
    name: "Outschool",
    url: "https://outschool.com/",
    provider: "Outschool",
    sourceType: "Course marketplace (model reference)",
    relatedTopics: ["course discovery", "age filters", "flexible browsing"],
    recommendedAgeRange: "3-18",
    usageInSchulab: "Inspiration only for marketplace/course discovery, age filters and flexible browsing. NOT a curriculum source.",
    status: "OPTIONAL",
  },
  {
    key: "google-cs-first",
    name: "Google CS First / Experience CS",
    url: "https://csfirst.withgoogle.com/",
    provider: "Google",
    sourceType: "CS curriculum (historical reference)",
    relatedTopics: ["computer science", "Scratch-based activities"],
    recommendedAgeRange: "8-14",
    usageInSchulab: "Historical inspiration only — not treated as an active core source.",
    status: "HISTORICAL",
  },
];
