// Task 4 — PR automation. Takes a prepared lesson folder (the orchestrator's
// output, Task 3) and opens a sync-compatible pull request into the
// STEM-Curricula repo. Human review = PR review; on merge, the platform's
// curriculum-sync ingests it. See docs/curriculum-production.
//
// The lesson folder must already match the repo conventions (meta.yml +
// handout.md + activity.md + quiz.md + presentation.md + resources.md), which
// the Lesson Builder / Publisher agents produce. This script only does the git
// + PR mechanics, with the "AI-assisted, human-reviewed" packet as the body.
//
// SAFE BY DEFAULT: dry-run prints the plan and writes nothing remote. Pass
// --execute to branch, commit, push, and open the PR.
//
// Usage:
//   npx tsx scripts/curriculum-agents/open-lesson-pr.ts \
//     --lesson <localLessonDir> \
//     --target <subjectRoot/course-slug/modules/module_xx/lesson-slug> \
//     [--repo <path>] [--title "..."] [--report <verification.json>] [--execute]

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, mkdirSync, copyFileSync, statSync } from "node:fs";
import { resolve, join, basename } from "node:path";

// Files the curriculum sync recognises in a lesson folder. meta.yml + handout
// are the minimum for a publishable lesson.
const KNOWN_LESSON_FILES = [
  "meta.yml",
  "handout.md",
  "handout.ar.md",
  "handout.de.md",
  "activity.md",
  "activity.ar.md",
  "activity.de.md",
  "presentation.md",
  "presentation.ar.md",
  "presentation.de.md",
  "tutor.md",
  "quiz.md",
  "quiz.yaml",
  "resources.md",
];
const REQUIRED = ["meta.yml", "handout.md"];

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
function flag(name: string): boolean {
  return process.argv.includes(name);
}

function git(repo: string, args: string[]): string {
  return execFileSync("git", ["-C", repo, ...args], { encoding: "utf8" }).trim();
}

interface VerificationReport {
  passed: boolean;
  issues?: { check: string; detail: string; section?: string; url?: string }[];
}

/** Pull the source/secondarySources block out of meta.yml as text for the PR body. */
function extractSources(metaYml: string): string {
  const lines = metaYml.split(/\r?\n/);
  const out: string[] = [];
  let capturing = false;
  for (const line of lines) {
    if (/^(source|secondarySources):/.test(line)) capturing = true;
    else if (capturing && /^\S/.test(line)) capturing = false; // next top-level key
    if (capturing) out.push(line);
  }
  return out.join("\n").trim();
}

function buildPrBody(opts: {
  lessonSlug: string;
  sources: string;
  report?: VerificationReport;
}): string {
  const checklist = [
    "Source exists & URL valid",
    "No invented facts / providers",
    "Age-appropriate",
    "Safe (no unsafe activity)",
    "No copied source text",
    "Clear learning objective",
    "Quiz matches lesson & answer keys correct",
    "Final project matches course",
    "Tutor note present",
    "Parent note present",
    "Lumo style consistent",
    "Localization complete (en/ar/de; RTL for ar)",
  ]
    .map((c) => `- [ ] ${c}`)
    .join("\n");

  let verification = "_No automated verification report attached._";
  if (opts.report) {
    if (opts.report.passed) {
      verification = "✅ Automated checks passed (coverage · over-copy · URL liveness).";
    } else {
      const issues = (opts.report.issues ?? [])
        .map((i) => `- ❌ **${i.check}**${i.section ? ` (${i.section})` : ""}${i.url ? ` ${i.url}` : ""}: ${i.detail}`)
        .join("\n");
      verification = `⚠️ Automated checks found issues — resolve before merge:\n${issues}`;
    }
  }

  return [
    "## AI-assisted, human-reviewed",
    "",
    `Generated lesson: \`${opts.lessonSlug}\`. Source-first + RAG-gated (Opus 4.8 / Sonnet 4.6).`,
    "",
    "### Automated verification",
    verification,
    "",
    "### Sources (from meta.yml)",
    opts.sources ? "```yaml\n" + opts.sources + "\n```" : "_none found in meta.yml_",
    "",
    "### Reviewer checklist (all must pass before merge)",
    checklist,
    "",
    "> Generated by the SchuLab curriculum pipeline (scripts/curriculum-agents). " +
      "Do not merge until a human reviewer signs off.",
    "",
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
  ].join("\n");
}

function listLessonFiles(dir: string): string[] {
  return readdirSync(dir).filter(
    (f) => statSync(join(dir, f)).isFile() && KNOWN_LESSON_FILES.includes(f)
  );
}

function main() {
  const lessonDir = arg("--lesson");
  const target = arg("--target");
  const repo = resolve(
    arg("--repo") ?? process.env.CURRICULA_REPO_PATH ?? "../STEM-Curricula"
  );
  const reportPath = arg("--report");
  const execute = flag("--execute");

  if (!lessonDir || !target) {
    console.error(
      "Usage: --lesson <dir> --target <subject/course/modules/module/lesson> [--repo <path>] [--report <json>] [--execute]"
    );
    process.exit(2);
  }

  const absLesson = resolve(lessonDir);
  if (!existsSync(absLesson)) throw new Error(`Lesson dir not found: ${absLesson}`);
  for (const req of REQUIRED) {
    if (!existsSync(join(absLesson, req))) {
      throw new Error(`Lesson dir missing required file: ${req}`);
    }
  }
  if (!existsSync(join(repo, ".git"))) {
    throw new Error(`Not a git repo: ${repo} (set --repo or CURRICULA_REPO_PATH)`);
  }
  const origin = git(repo, ["remote", "get-url", "origin"]);
  if (!/STEM-Curricula/i.test(origin)) {
    throw new Error(`Repo origin is not STEM-Curricula: ${origin}`);
  }

  const files = listLessonFiles(absLesson);
  const lessonSlug = basename(target);
  const branch = `ai/lesson/${lessonSlug}`;
  const meta = readFileSync(join(absLesson, "meta.yml"), "utf8");
  const sources = extractSources(meta);
  const report: VerificationReport | undefined = reportPath
    ? (JSON.parse(readFileSync(resolve(reportPath), "utf8")) as VerificationReport)
    : undefined;
  const title = arg("--title") ?? `feat(ai): ${lessonSlug}`;
  const body = buildPrBody({ lessonSlug, sources, report });
  const targetPath = join(repo, target);

  // ── Plan (always printed) ──────────────────────────────────────────────
  console.log("── Lesson PR plan ────────────────────────────────────────");
  console.log(`Repo        : ${repo} (${origin})`);
  console.log(`Branch      : ${branch}`);
  console.log(`Target path : ${target}`);
  console.log(`Files       : ${files.join(", ")}`);
  console.log(`PR title    : ${title}`);
  console.log(`Verification: ${report ? (report.passed ? "passed" : "HAS ISSUES") : "none attached"}`);
  if (report && !report.passed) {
    console.log("⚠  Verification has unresolved issues — the PR will be opened as a draft for fixing.");
  }
  console.log("──────────────────────────────────────────────────────────");

  if (!execute) {
    console.log("\nDRY RUN — nothing written or pushed. Re-run with --execute to open the PR.\n");
    console.log("PR body preview:\n");
    console.log(body);
    return;
  }

  // ── Execute ────────────────────────────────────────────────────────────
  git(repo, ["checkout", "main"]);
  git(repo, ["pull", "--ff-only", "origin", "main"]);
  git(repo, ["checkout", "-B", branch]);

  mkdirSync(targetPath, { recursive: true });
  for (const f of files) copyFileSync(join(absLesson, f), join(targetPath, f));
  // Copy any asset subdirs the lesson references (images, etc.).
  for (const entry of readdirSync(absLesson)) {
    const src = join(absLesson, entry);
    if (statSync(src).isDirectory()) {
      copyDirRecursive(src, join(targetPath, entry));
    }
  }

  git(repo, ["add", target]);
  git(repo, ["commit", "-m", title]);
  git(repo, ["push", "-u", "origin", branch, "--force-with-lease"]);

  const draft = report && !report.passed ? ["--draft"] : [];
  const prUrl = execFileSync(
    "gh",
    [
      "pr",
      "create",
      "--repo",
      "Schulab-LMS/STEM-Curricula",
      "--base",
      "main",
      "--head",
      branch,
      "--title",
      title,
      "--body",
      body,
      ...draft,
    ],
    { cwd: repo, encoding: "utf8" }
  ).trim();
  console.log(`\n✅ PR opened: ${prUrl}`);
}

function copyDirRecursive(src: string, dest: string): void {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const s = join(src, entry);
    const d = join(dest, entry);
    if (statSync(s).isDirectory()) copyDirRecursive(s, d);
    else copyFileSync(s, d);
  }
}

main();
